// Generated by CoffeeScript 1.4.0

module.exports = function(grunt) {
  grunt.initConfig({
    concat: {
      milkpack: {
        src: ['src/Milkpack.coffee', 'src/MilkpackEvent.coffee', 'src/Scene.coffee', 'src/SceneEvent.coffee', 'src/SceneStatus.coffee', 'src/Util.coffee'],
        dest: 'tmp/milkpack-concat.coffee'
      }
    },
    coffee: {
      milkpack: {
        files: {
          'lib/milkpack.js': 'tmp/milkpack-concat.coffee'
        }
      },
      example: {
        files: {
          'example/official/script/main.js': 'example/official/coffee/main.coffee'
        }
      },
      kazitori: {
        files: {
          'example/official/script/kazitori.js': 'example/official/coffee/kazitori.coffee'
        },
        options: {
          bare: true
        }
      }
    },
    min: {
      milkpack: {
        src: 'lib/milkpack.js',
        dest: 'lib/milkpack.min.js'
      }
    },
    less: {
      example: {
        src: 'example/official/less/main.less',
        dest: 'example/official/style/main.css'
      }
    },
    watch: {
      script: {
        files: ['src/**/*.coffee', 'example/official/coffee/*.coffee'],
        tasks: 'default'
      },
      style: {
        files: 'example/official/less/*.less',
        tasks: 'default'
      }
    }
  });
  grunt.loadNpmTasks('grunt-contrib');
  grunt.registerTask('default', 'concat coffee min less');
  grunt.registerTask("r", "reload Google Chrome (OS X)", function() {
    return require("child_process").exec('osascript -e \'tell application \"Google Chrome\" to tell the active tab of its first window to reload\'');
  });
  return grunt.registerTask('w', 'watch');
};
